version: "3.3"

volumes:
  data:

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - ./.env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
